
# CONFIG VARS
#######################################################

NAME	= "jbarment"
# Masta
M_NAME  = 'JoepiS'
M_IP    = ENV['M_IP'] || '192.168.42.110'

# Slave
S_NAME  = 'JoepiSW'
S_IP    = ENV['S_IP'] || '192.168.42.111'

# V_box
RAM     = 4096
CPUS    = 3

#######################################################


Vagrant.configure("2") do |config|
	config.vm.box 				= "joepyjoep/CentosVB"
	config.vm.box_version 		= "1.0"
	config.vm.box_check_update 	= false
	config.vm.hostname 			= "jbarment"
	config.vm.synced_folder 	".", "/vagrant", type: "virtualbox"
	

	if Vagrant.has_plugin?("vagrant-vbguest") then
		config.vbguest.auto_update 			= false
		config.vbguest.installer_options 	= { allow_kernel_upgrade: true }
	end

	config.vm.provider "virtualbox" do |vbox|
		vbox.memory 	= RAM
		vbox.cpus 		= CPUS
		vbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vbox.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

	config.vm.define M_NAME do |masta|
		masta.vm.hostname 	= M_NAME
		masta.vm.network 	"private_network", ip: M_IP
		masta.vm.provision 	"shell", privileged: true, path: "masta.sh", args: [M_IP]

		masta.vm.provider 	"virtualbox" do |vbox|
			vbox.name = M_NAME
		end
	end
  
	config.vm.define S_NAME do |slave|
		slave.vm.hostname 	= S_NAME
		slave.vm.network 	"private_network", ip: S_IP
		slave.vm.provision 	"shell", privileged: true, path: "slave.sh", args: [M_IP, S_IP]

		slave.vm.provider 	"virtualbox" do |vbox|
			vbox.name = S_NAME
		end
	end
end
  